### ISSUE TITLE
PHP Fatal Error - Call to Undefined Function

### ISSUE THREAD

**Issue by qrahaman** [renatonascalves/wp-graphql-buddypress#119]
### Description of the bug

Followed instructions here: https://github.com/renatonascalves/wp-graphql-buddypress

The logged error is noted below.

### Steps To Reproduce

Step 1 I am using BuddyBoss, not BuddyPress (hopefully that isn't the issue)
Step 4 was run before activating the plugin.  Then attempted to activate the plugin which generated the fatal error.

### Additional Information

2023/08/13 22:47:23 [error] 33433#33433: *8591 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function WPGraphQL\Extensions\BuddyPress\bp_get_group_type_tax_name() in /www/pickleballersnetwork_949/public/wp-content/plugins/wp-graphql-buddypress-main/src/TypeRegistry.php:240
Stack trace:
#0 /www/pickleballersnetwork_949/public/wp-includes/class-wp-hook.php(312): WPGraphQL\Extensions\BuddyPress\TypeRegistry::WPGraphQL\Extensions\BuddyPress\{closure}(Array, 'category')
#1 /www/pickleballersnetwork_949/public/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /www/pickleballersnetwork_949/public/wp-includes/class-wp-taxonomy.php(316): apply_filters('register_taxono...', Array, 'category', Array)
#3 /www/pickleballersnetwork_949/public/wp-includes/class-wp-taxonomy.php(290): WP_Taxonomy->set_props('post', Array)
#4 /www/pickleballersnetwork_949/public/wp-includes/taxonomy.php(493): WP_Taxonomy->__construct('category', 'post', Array)
#5 /www/pickleballersnetwork_949/public/wp-includes/taxonomy.php(82): register_ta" while reading response header from upstream, client: 174.68.181.157, server: staging-pickleballersnetwork.kinsta.cloud, request: "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-pickleballersnetwork.sock:", host: "staging-pickleballersnetwork.kinsta.cloud:61745", referrer: "https://staging-pickleballersnetwork.kinsta.cloud/wp-admin/plugins.php?plugin_status=all&paged=1&s"

**Comment by renatonascalves** [comment]
@qrahaman Have you tried with BuddyPress instead? I'm not sure this plugin works with BuddyBoss.

**Comment by renatonascalves** [comment]
When BuddyPress is available, this function is also available: https://github.com/buddypress/buddypress/blob/67fc8615ccb9d94da62ba588d1e5f520fc3cb8af/src/bp-groups/bp-groups-functions.php#L2655

Your error `Call to undefined function WPGraphQL\Extensions\BuddyPress\bp_get_group_type_tax_name() in` tells me that BuddyBoss either removed it or doesn't have a similar version, hence why it is trying to get the version from the plugin namespace.

**Comment by renatonascalves** [comment]
Will resolve the ticket as invalid.
